apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: demo
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Daemon        off
        Log_Level     info
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    [INPUT]
        Name           tail
        Tag            kubernetes.*
        Path           /var/log/containers/*.log
        Parser         docker
        DB             /var/flb/tdb
        Mem_Buf_Limit  50MB
        Skip_Long_Lines   On
        Refresh_Interval 5

    [OUTPUT]
        Name            loki
        Match           *
        Url             http://loki:3100/loki/api/v1/push
        RemoveKeys      kubernetes.*
        BatchWait       5
        BatchSize       5
        BatchCount      10
        Replace_Dots    On
        HTTP_Debug      On
        Loki_Tag_Key    kubernetes_pod_name
        Loki_Prefix     true

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-bit
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:1.9
          ports:
            - containerPort: 2020
          volumeMounts:
            - name: config-volume
              mountPath: /fluent-bit/etc/
            - name: varlog
              mountPath: /var/log
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: fluent-bit-config
        - name: varlog
          hostPath:
            path: /var/log
---
