apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: demo
spec:
  selector:
    app: loki
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:latest
        ports:
        - containerPort: 3100

---
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: loki-datasource
  namespace: demo
spec:
  name: Loki
  type: Loki
  url: http://loki:3100
  jsonData:
    maxLines: 1000
    showTime: true

---
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDashboard
metadata:
  name: loki-dashboard
  namespace: demo
spec:
  json: |
    {
      "dashboard": {
        "id": null,
        "title": "Loki Logs",
        "panels": [
          {
            "title": "Loki Logs",
            "type": "logs",
            "datasource": "Loki",
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 0,
              "y": 0
            }
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "timezone": "browser",
        "version": 8
      },
      "folderId": null,
      "overwrite": false
    }
