apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector-sidecar
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector-sidecar
  template:
    metadata:
      labels:
        app: otel-collector-sidecar
    spec:
      containers:
        - name: otel-collector-sidecar
          image: otel/opentelemetry-collector-contrib:0.78.0
          args: ["--config=/etc/otel-collector-config.yaml"]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/otel-collector-config.yaml
              subPath: otel-collector-config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: otel-collector-configmap
            items:
              - key: otel-collector-config.yaml
                path: otel-collector-config.yaml

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-sidecar-configmap
  namespace: demo
data:
  otel-collector-config-sidecar.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:3030"

    exporters:
      logging:
      loki:
        endpoint: http://loki:3100/loki/api/v1/push
      prometheus:
        endpoint: "0.0.0.0:8889"

    service:
      pipelines:
        logs:
          receivers: [otlp]
          exporters: [loki]
        traces:
          receivers: [otlp]
          exporters: [logging]
        metrics:
          receivers: [otlp]
          exporters: [logging,prometheus]
